ansible_host: 188.245.69.206
server_domain: static.206.69.245.188.clients.your-server.de
configure_tls: true
admin_email: tiagodepalves@gmail.com
runner_password: $y$jFT$gfbd6pgR7SkbmwBxM1pIp0$8AJO9OAl0b3dNLMg5HJcNOzkWCYcVezsBDkPMr3Zkm6
