- name: Set Grafana nginx endpoint
  ansible.builtin.template:
    src: grafana.conf.j2
    dest: /etc/nginx/default.d/grafana.conf
    owner: root
    group: root
    mode: '0644'
  when: ansible_facts["user_id"] == "root"
  notify: Reload nginx

- name: Configure Grafana
  block:
    - name: Create config directory
      ansible.builtin.file:
        path: /home/runner/.config/grafana
        state: directory
        owner: runner
        group: runner
        mode: '0700'

    - name: Create directory tree
      ansible.builtin.file:
        path: /home/runner/.config/grafana/{{ item }}
        state: directory
        owner: runner
        group: runner
        mode: '0755'
      loop:
        - provisioning/datasources
        - provisioning/dashboards
        - provisioning/alerting
        - provisioning/plugins
        - dashboards
        - scrape

    - name: Configure grafana.ini
      ansible.builtin.template:
        src: grafana.ini.j2
        dest: /home/runner/.config/grafana/grafana.ini
        owner: runner
        group: runner
        mode: '0644'
      notify: Restart Grafana

    - name: Copy Grafana provisioning
      ansible.builtin.copy:
        src: '{{ item }}'
        dest: /home/runner/.config/grafana/{{ item }}
        owner: runner
        group: runner
        mode: '0644'
      loop:
        - provisioning/datasources/victoriametrics.yaml
        - provisioning/dashboards/dashboards.yaml
        - dashboards/9964_rev1.json
      notify: Restart Grafana

    - name: Copy VictoriaMetrics scrape config
      ansible.builtin.copy:
        src: scrape/promscrape.yaml
        dest: /home/runner/.config/grafana/scrape/promscrape.yaml
        owner: runner
        group: runner
        mode: '0644'
      notify: Restart VictoriaMetrics

- name: Set up Grafana services
  block:
    - name: Create Grafana Podman secrets
      containers.podman.podman_secret:
        name: grafana-admin-password
        data: '{{ grafana_admin_password }}'
        state: present
        force: true
      become: '{{ ansible_facts["user_id"] != "runner" }}'
      become_user: runner
      become_method: su
      become_flags: -l
      no_log: true
      notify: Restart Grafana

    - name: Copy Grafana quadlets
      ansible.builtin.copy:
        src: quadlets/{{ item }}
        dest: /home/runner/.config/containers/systemd/{{ item }}
        owner: runner
        group: runner
        mode: '0600'
      loop:
        - grafana.container
        - grafana-data.volume
      notify: Restart Grafana

    - name: Copy VictoriaMetrics quadlets
      ansible.builtin.copy:
        src: quadlets/{{ item }}
        dest: /home/runner/.config/containers/systemd/{{ item }}
        owner: runner
        group: runner
        mode: '0600'
      loop:
        - victoriametrics.container
        - victoriametrics-data.volume
      notify: Restart VictoriaMetrics

- name: Reload services
  meta: flush_handlers

- name: Enable and start Grafana quadlets
  ansible.builtin.systemd_service:
    name: grafana
    scope: user
    enabled: true
    state: started
  become: '{{ ansible_facts["user_id"] != "runner" }}'
  become_user: runner
  become_method: su
  become_flags: -l
