## template: jinja
#cloud-config

hostname: '{{ v1.local_hostname }}'
ssh_pwauth: false # authorized keys only

users:
  - name: runner
    groups: [wheel]
    shell: /bin/bash
    lock_passwd: false # allow password locally
    passwd: $y$jFT$gfbd6pgR7SkbmwBxM1pIp0$8AJO9OAl0b3dNLMg5HJcNOzkWCYcVezsBDkPMr3Zkm6
    ssh_authorized_keys: # prefer `-sk` (FIDO/U2F) keys
      - sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAINczWuNAtwE1eBt9quk1HmbzGdLlGDb7BBL6SgUFay8QAAAABHNzaDo= marmis@marmis-arch
      - sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAILBqGX/KZaYWuWIHBR4CQu7rgnfKYbr57fPnerlCA1FyAAAABHNzaDo= marmis@marmis-samsung
      - sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAID0FKhzEMNixWGnA2fZy7oP9yf1vbnFhTc+0jg6bbxHhAAAABHNzaDo= marmis@dev-sec-ops-tiago

package_reboot_if_required: true
package_update: true
package_upgrade: true
packages:
  - kitty-terminfo
  - nginx
  - certbot
  - python3-certbot-nginx
  - podman
  - crun-krun
  - passt

resolv_conf:
  options:
    edns0: true
    trust-ad: true

write_files:
  - path: /etc/nginx/sites-available/jenkins.conf
    owner: nginx:nginx
    permissions: '0444'
    content: |
      {% set domain = "static.206.69.245.188.clients.your-server.de" -%}
      limit_req_zone $binary_remote_addr zone=jenkins_limit:10m rate=10r/s;

      # HTTP  redirect to HTTPS
      server {
        listen 80;
        listen [::]:80;

        server_name {{ domain }};

        return 301 https://$host$request_uri;
      }

      # HTTPS with TLS certificates and proxy to Jenkins
      server {
        listen 443 ssl;
        listen [::]:443 ssl;

        http2 on;

        server_name {{ domain }};

        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:10m;
        ssl_session_tickets off;

        # Proxy everything to Jenkins on localhost:8080
        location / {
          limit_req zone=jenkins_limit burst=20 nodelay;

          proxy_pass         http://127.0.0.1:8080;
          proxy_set_header   Host $host;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Proto $scheme;
        }
      }

  - path: /etc/containers/containers.conf.d/10-compose-warnings.conf
    owner: root:root
    permissions: '0644'
    content: |
      [engine]
      compose_warning_logs = true

  - path: /etc/containers/containers.conf.d/30-compression.conf
    owner: root:root
    permissions: '0644'
    content: |
      [engine]
      compression_format = "zstd"
      compression_level = 5

  - path: /etc/containers/containers.conf.d/31-downloads.conf
    owner: root:root
    permissions: '0644'
    content: |
      [engine]
      image_parallel_copies = 12

  - path: /etc/containers/containers.conf.d/50-runtime.conf
    owner: root:root
    permissions: '0644'
    content: |
      [engine]
      runtime = "krun"

  - path: /etc/containers/containers.conf.d/51-dns-options.conf
    owner: root:root
    permissions: '0644'
    content: |
      [containers]
      dns_options = ["edns0", "trust-ad"]

  - path: /etc/ssh/sshd_config.d/20-authentication.conf
    owner: root:root
    permissions: '0440'
    content: |
      # Deny root access
      PermitRootLogin no

      # Enable public key
      AuthenticationMethods publickey
      PubkeyAuthentication yes

      # Disable password
      PasswordAuthentication no
      KbdInteractiveAuthentication no

  - path: /etc/ssh/sshd_config.d/50-algorithms.conf
    owner: root:root
    permissions: '0440'
    content: |
      # Recommended
      KexAlgorithms sntrup761x25519-sha512,sntrup761x25519-sha512@openssh.com,mlkem768x25519-sha256,curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group18-sha512,diffie-hellman-group16-sha512,diffie-hellman-group-exchange-sha256
      HostKeyAlgorithms ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,sk-ssh-ed25519@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256
      MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com
      Ciphers aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr

      # Insecure
      KexAlgorithms -ecdh-sha2-nistp*,diffie-hellman-group14-sha256
      HostKeyAlgorithms -ecdsa-sha2-nistp*,sk-ecdsa-sha2-nistp*
      MACs -hmac-sha1*,hmac-sha2-256,hmac-sha2-512,umac-64*,umac-128@openssh.com
      Ciphers -chacha20-poly1305@openssh.com

runcmd:
  - [loginctl, enable-linger, runner]
  - [ln, -s, /etc/nginx/sites-available/jenkins.conf, /etc/nginx/sites-enabled/jenkins.conf]
  - [systemctl, enable, --now, nginx]
  - |
    certbot certonly --nginx {% if staging %}--staging{% endif %} -d '{{ domain }}' -m tiagodepalves@gmail.com --agree-tos -n]
  - [systemctl, reload, nginx]
