[containers]
log_driver = "journald"
log_tag = "container/{{.Name}}"
dns_options = ["edns0", "trust-ad"]

[engine]
runtime = "krun"
image_parallel_copies = 12
compression_format = "zstd"
compression_level = 5
compose_warning_logs = true
