## template: jinja
#cloud-config

# see https://wiki.archlinux.org/title/Arch_Linux_on_a_VPS#Hetzner_Cloud
# and https://community.hetzner.com/tutorials/basic-cloud-config
vendor_data:
  enabled: false

hostname: '{{ v1.local_hostname }}'
ssh_pwauth: false # authorized keys only

users:
  - name: runner
    groups: [wheel]
    shell: /usr/bin/bash
    lock_passwd: false # allow password locally
    passwd: $y$jFT$gfbd6pgR7SkbmwBxM1pIp0$8AJO9OAl0b3dNLMg5HJcNOzkWCYcVezsBDkPMr3Zkm6
    ssh_authorized_keys: # prefer `-sk` (FIDO/U2F) keys
      - sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAINczWuNAtwE1eBt9quk1HmbzGdLlGDb7BBL6SgUFay8QAAAABHNzaDo= marmis@marmis-arch
      - sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAILBqGX/KZaYWuWIHBR4CQu7rgnfKYbr57fPnerlCA1FyAAAABHNzaDo= marmis@marmis-samsung
      - sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAID0FKhzEMNixWGnA2fZy7oP9yf1vbnFhTc+0jg6bbxHhAAAABHNzaDo= marmis@dev-sec-ops-tiago

package_reboot_if_required: true
package_update: true
packages:
  - git
  # Server networking:
  - nginx
  - certbot
  - python3-certbot-nginx
  # Local services:
  - podman
  - crun-krun
  - passt
  # Interactive tools:
  - bat
  - fd-find
  - fzf
  - du-dust
  - kitty-terminfo
  - nano
  - ncurses-term
  - ripgrep

resolv_conf:
  options:
    edns0: true
    trust-ad: true

write_files:
  - path: /etc/nginx/conf.d/jenkins.conf
    owner: root:root
    permissions: '0644'
    content: |
      {% set domain = "static.206.69.245.188.clients.your-server.de" -%}
      limit_req_zone $binary_remote_addr zone=jenkins_limit:10m rate=10r/s;

      server {
        listen 80;
        listen [::]:80;

        server_name {{ domain }};

        # Proxy everything to Jenkins on localhost:8080
        location / {
          limit_req zone=jenkins_limit burst=20 nodelay;

          proxy_pass        http://127.0.0.1:8080;
          proxy_set_header  Host $host;
          proxy_set_header  X-Real-IP $remote_addr;
          proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header  X-Forwarded-Proto $scheme;
          proxy_buffering   off;
        }
      }

  - path: /etc/containers/containers.conf.d/99-custom.conf
    owner: root:root
    permissions: '0644'
    content: |
      [containers]
      log_driver = "journald"
      log_tag = "container/{% raw %}{{.Name}}{% endraw %}"
      dns_options = ["edns0", "trust-ad"]

      [engine]
      runtime = "krun"
      image_parallel_copies = 12
      compression_format = "zstd"
      compression_level = 5
      compose_warning_logs = true

  - path: /etc/profile.d/sh.local
    owner: root:root
    permissions: '0644'
    content: |
      # for interactive shells only
      if [[ $- == *i* ]]; then
        GREEN="\[$(tput setaf 2)\]"
        ORANGE="\[$(tput setaf 11)\]"
        RESET="\[$(tput sgr0)\]"
        PS1="${GREEN}[${ORANGE}\u@\h${RESET} \W${GREEN}]\$${RESET} "
        if command -v fzf > /dev/null; then
          eval "$(fzf --bash)"
        fi
        unset GREEN ORANGE RESET
      fi

ansible:
  install_method: distro
  package_name: ansible
  pull:
    - url: '{{ ds.meta_data.ansible_pull_url | default("https://github.com/Pipeline-DevSecOps-para-Blockchain-2025/jenkins-server-config.git") }}'
      playbook_names:
        - playbooks/fedora-cloud.yaml
        - playbooks/common.yaml
      connection: local

runcmd:
  - [loginctl, enable-linger, runner]
  - [systemctl, enable, --now, nginx.service]
  - |
    {% if ds and ds.meta_data and ds.meta_data.notls -%}
    echo 'TLS disabled'
    {%- else -%}
    certbot run --nginx -d '{{ domain }}' --redirect --hsts --staple-ocsp -m tiagodepalves@gmail.com --agree-tos -n
    systemctl enable --now certbot-renew.timer
    {%- endif %}
    # identation guard
  - [systemctl, reload, nginx.service]
