## template: jinja
#cloud-config

# see https://wiki.archlinux.org/title/Arch_Linux_on_a_VPS#Hetzner_Cloud
# and https://community.hetzner.com/tutorials/basic-cloud-config
vendor_data:
  enabled: false

hostname: '{{ v1.local_hostname }}'
ssh_pwauth: false # authorized keys only

users:
  - name: runner
    groups: [wheel]
    shell: /usr/bin/bash
    lock_passwd: false # allow password locally
    passwd: $y$jFT$gfbd6pgR7SkbmwBxM1pIp0$8AJO9OAl0b3dNLMg5HJcNOzkWCYcVezsBDkPMr3Zkm6
    ssh_authorized_keys: # prefer `-sk` (FIDO/U2F) keys
      - sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAINczWuNAtwE1eBt9quk1HmbzGdLlGDb7BBL6SgUFay8QAAAABHNzaDo= marmis@marmis-arch
      - sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAILBqGX/KZaYWuWIHBR4CQu7rgnfKYbr57fPnerlCA1FyAAAABHNzaDo= marmis@marmis-samsung
      - sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAID0FKhzEMNixWGnA2fZy7oP9yf1vbnFhTc+0jg6bbxHhAAAABHNzaDo= marmis@dev-sec-ops-tiago

resolv_conf:
  options:
    edns0: true
    trust-ad: true

packages:
  - git

# https://docs.cloud-init.io/en/latest/reference/modules.html#ansible
ansible:
  install_method: distro
  package_name: ansible
  pull:
    - url: '{{ ds.meta_data.ansible_pull_url | default("https://github.com/Pipeline-DevSecOps-para-Blockchain-2025/jenkins-server-config.git") }}'
      playbook_names:
        - playbooks/fedora-cloud.yaml
        - playbooks/common.yaml
        - playbooks/jenkins.yaml
      connection: local

reporting:
  logs:
    type: log
    level: INFO
  stdout:
    type: print

runcmd:
  - [loginctl, enable-linger, runner]
