- name: Install interactive tools
  ansible.builtin.package:
    name:
      - bat
      - fd-find
      - fzf
      - du-dust
      - kitty-terminfo
      - nano
      - ncurses-term
      - ripgrep
    state: present

- name: Configure shell profile
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /etc/{{ item }}
    owner: root
    group: root
    mode: '0644'
  loop:
    - environment
    - profile.d/sh.local
  notify: Restart serial consoles

- name: Update serial console
  block:
    - name: Create serial-getty@.service.d
      ansible.builtin.file:
        path: /etc/systemd/system/serial-getty@.service.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Configure serial console
      ansible.builtin.copy:
        src: serial-getty@.service.d/default-terminfo.conf
        dest: /etc/systemd/system/serial-getty@.service.d/default-terminfo.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart serial consoles
