{
 "title": "Jenkins overview",
 "description": "The dashboard displays the status of your Jenkins jobs, the status of the queue on executors, and a few other things.\r\nThe metrics you get are taken from the Prometheus plugin for your Jenkins.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(up{job=\"jenkins\"}, instance)"
    }
   },
   {
    "name": "workers_label",
    "label": "workers_label",
    "query": {
     "query": "label_values(jenkins_executors_defined, label)"
    }
   },
   {
    "name": "jenkins_job",
    "label": "jenkins_job",
    "query": {
     "query": "label_values(jenkins_builds_last_build_duration_milliseconds, jenkins_job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Job info",
   "type": "table",
   "gridPos": { "h": 28, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(jenkins_builds_last_build_start_time_milliseconds{jenkins_job=~\"$jenkins_job\", instance=~\"$instance\"}, \"job_url\", \"$1/job/$2\", \"jenkins_job\", \"(.*)/(.*)\")",
     "legendFormat": "{{jenkins_job}}"
    },
    {
     "expr": "label_replace(avg_over_time(jenkins_builds_last_build_duration_milliseconds{jenkins_job=~\"$jenkins_job\", instance=~\"$instance\"}[7d]), \"job_url\", \"$1/job/$2\", \"jenkins_job\", \"(.*)/(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(jenkins_builds_last_build_duration_milliseconds{jenkins_job=~\"$jenkins_job\", instance=~\"$instance\"}, \"job_url\", \"$1/job/$2\", \"jenkins_job\", \"(.*)/(.*)\")",
     "legendFormat": "{{jenkins_job}}"
    },
    {
     "expr": "label_replace(jenkins_builds_last_build_result_ordinal{jenkins_job=~\"$jenkins_job\", instance=~\"$instance\"}, \"job_url\", \"$1/job/$2\", \"jenkins_job\", \"(.*)/(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last build result",
   "type": "stat",
   "gridPos": { "h": 15, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(jenkins_builds_last_build_result_ordinal{jenkins_job=~\"$jenkins_job\", instance=~\"$instance\"}, \"job_url\", \"$1/job/$2\", \"jenkins_job\", \"(.*)/(.*)\")",
     "legendFormat": "{{jenkins_job}}"
    }
   ]
  },
  {
   "title": "Builds health",
   "type": "stat",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(jenkins_builds_health_score{jenkins_job=~\"$jenkins_job\", instance=~\"$instance\"}, \"job_url\", \"$1/job/$2\", \"jenkins_job\", \"(.*)/(.*)\")",
     "legendFormat": "{{jenkins_job}}"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Not succesful builds list",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(job) (jenkins_builds_last_build_result_ordinal{jenkins_job=~\"$jenkins_job\", instance=~\"$instance\"} == -1)",
     "legendFormat": "Running"
    },
    {
     "expr": "count by(job) (jenkins_builds_last_build_result_ordinal{jenkins_job=~\"$jenkins_job\", instance=~\"$instance\"} == 1)",
     "legendFormat": "Unstable"
    },
    {
     "expr": "count by(job) (jenkins_builds_last_build_result_ordinal{jenkins_job=~\"$jenkins_job\", instance=~\"$instance\"} == 2)",
     "legendFormat": "Failed"
    },
    {
     "expr": "count by(job) (jenkins_builds_last_build_result_ordinal{jenkins_job=~\"$jenkins_job\", instance=~\"$instance\"} == 4)",
     "legendFormat": "Aborted"
    }
   ]
  },
  {
   "title": "Jenkins health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_health_check_score{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Jenkins nodes offline",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_node_offline_value{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Jenkins nodes online",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_node_online_value{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "JVM Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_uptime_milliseconds{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Executors global",
   "type": "stat",
   "gridPos": { "h": 15, "w": 9, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jenkins_executors_connecting{instance=~\"$instance\"}) by (workers_label)",
     "legendFormat": "Connecting"
    },
    {
     "expr": "sum(jenkins_executors_defined{instance=~\"$instance\"}) by (workers_label)",
     "legendFormat": "Defined"
    },
    {
     "expr": "sum(jenkins_executors_online{instance=~\"$instance\"}) by (workers_label)",
     "legendFormat": "Online"
    },
    {
     "expr": "sum(jenkins_executors_idle{instance=~\"$instance\"}) by (workers_label)",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum(jenkins_executors_available{instance=~\"$instance\"}) by (workers_label)",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(jenkins_executors_busy{instance=~\"$instance\"}) by (workers_label)",
     "legendFormat": "Busy"
    }
   ]
  },
  {
   "title": "Queue global",
   "type": "stat",
   "description": "Количество Job-ов в очереди глобально",
   "gridPos": { "h": 15, "w": 3, "x": 21, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (jenkins_executors_queue_length{instance=~\"$instance\"}) by (workers_label)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed jobs for [$interval]",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(count((count_over_time((jenkins_builds_last_build_result_ordinal{jenkins_job=~\"$jenkins_job\",instance=~\"$instance\"} == 2)[$interval:])) > (count_over_time((jenkins_builds_last_build_result_ordinal{jenkins_job=~\"$jenkins_job\",instance=~\"$instance\"} offset 1m == 2)[$interval:]))) by (jenkins_job, instance, job_url), \"job_url\", \"$1/job/$2\", \"jenkins_job\", \"(.*)/(.*)\")",
     "legendFormat": "{{jenkins_job}}"
    }
   ]
  },
  {
   "title": "Total running jobs for [$interval]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(jenkins_node_builds_count{instance=~\"$instance\",node=\"master\"}[$interval])"
    }
   ]
  },
  {
   "title": "Success jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(job) (jenkins_builds_last_build_result_ordinal{jenkins_job=~\"$jenkins_job\", instance=~\"$instance\"} == 0)",
     "legendFormat": "Total success jobs"
    }
   ]
  },
  {
   "title": "Queue global",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (jenkins_executors_queue_length{instance=~\"$instance\"}) by (label) >= 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executors for $workers_label",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "repeat": "workers_label",
   "collapsed": true,
   "panels": [
    {
     "title": "Usage executor on $workers_label",
     "type": "stat",
     "gridPos": { "h": 5, "w": 19, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jenkins_executors_connecting{label=~\"$workers_label\",instance=~\"$instance\"}",
       "legendFormat": "Connecting"
      },
      {
       "expr": "jenkins_executors_defined{label=~\"$workers_label\",instance=~\"$instance\"}",
       "legendFormat": "Defined"
      },
      {
       "expr": "jenkins_executors_online{label=~\"$workers_label\",instance=~\"$instance\"}",
       "legendFormat": "Online"
      },
      {
       "expr": "jenkins_executors_idle{label=~\"$workers_label\",instance=~\"$instance\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "jenkins_executors_available{label=~\"$workers_label\",instance=~\"$instance\"}",
       "legendFormat": "Available"
      },
      {
       "expr": "jenkins_executors_busy{label=~\"$workers_label\",instance=~\"$instance\"}",
       "legendFormat": "Busy"
      }
     ]
    },
    {
     "title": "Queue on $workers_label",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 61 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jenkins_executors_queue_length{label=~\"$workers_label\",instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}