users:
  marmis:
    name: Tiago de Paula
    email: tiagodepalves@gmail.com
    timezone: America/Sao_Paulo
    jenkins_password: $2a$12$RbH1rcNj.w/6DojPCw/1vuwlaLOD4MFD1f2avRWiDcqqMlzYdxOxC
    ssh_key: |
      sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAID0FKhzEMNixWGnA2fZy7oP9yf1vbnFhTc+0jg6bbxHhAAAABHNzaDo= marmis@dev-sec-ops-tiago
      sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAINczWuNAtwE1eBt9quk1HmbzGdLlGDb7BBL6SgUFay8QAAAABHNzaDo= marmis@marmis-arch
      sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAILBqGX/KZaYWuWIHBR4CQu7rgnfKYbr57fPnerlCA1FyAAAABHNzaDo= marmis@marmis-samsung
