- name: Restart Jenkins
  ansible.builtin.systemd_service:
    scope: user
    name: jenkins
    state: restarted
    daemon_reload: true
  become: '{{ ansible_facts["user_id"] != "runner" }}'
  become_user: runner
  become_method: su
  become_flags: -l
