- name: Restart Jenkins
  ansible.builtin.systemd_service:
    name: jenkins
    scope: user
    state: restarted
    daemon_reload: true
  become: '{{ ansible_facts["user_id"] != "runner" }}'
  become_user: runner
  become_method: su
  become_flags: -l

- name: Restart dockerd
  ansible.builtin.systemd_service:
    name: dockerd
    scope: user
    state: restarted
    daemon_reload: true
  become: '{{ ansible_facts["user_id"] != "runner" }}'
  become_user: runner
  become_method: su
  become_flags: -l
