- name: Install Podman
  ansible.builtin.package:
    name:
      - podman
      - passt
    state: present

- name: Create config override directory
  ansible.builtin.file:
    path: /etc/containers/containers.conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure containers
  ansible.builtin.copy:
    src: containers.conf.d/99-custom.conf
    dest: /etc/containers/containers.conf.d/99-custom.conf
    owner: root
    group: root
    mode: '0644'
