- name: Reload user systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: user
  become: '{{ ansible_facts["user_id"] != "runner" }}'
  become_user: runner
  become_method: su
  become_flags: '-l'
