- name: Restart VictoriaMetrics
  ansible.builtin.systemd_service:
    name: victoriametrics
    state: restarted
    scope: user
    daemon_reload: true
  become: '{{ ansible_facts["user_id"] != "runner" }}'
  become_user: runner
  become_method: su
  become_flags: -l

- name: Restart Grafana
  ansible.builtin.systemd_service:
    name: grafana
    state: restarted
    scope: user
    daemon_reload: true
  become: '{{ ansible_facts["user_id"] != "runner" }}'
  become_user: runner
  become_method: su
  become_flags: -l
