- name: System setup
  hosts: all
  become: true
  become_user: root
  tags: [system]
  roles:
    - role: dnf
      when: '"fedora" in group_names'
    - role: firewalld
    - role: unprivileged_user
    - role: nginx
    - role: sshd
    - role: certbot
      when: configure_tls
    - role: interactive_tools
    - role: podman

- name: Service deployment
  hosts: all
  tags: [services]
  roles:
    - role: jenkins
    - role: grafana
