- name: Service deployment
  hosts: all
  pre_tasks:
    - name: Load vault secrets
      ansible.builtin.include_vars:
        file: '{{ inventory_dir }}/secret_vars/{{ inventory_hostname }}.yaml'
      tags: [always]
      when: '"bootstrap" not in ansible_run_tags'
      no_log: true
  roles:
    - role: dnf
      when: '"fedora" in group_names'
      tags: [system]
    - role: firewalld
      tags: [system]
    - role: unprivileged_user
      tags: [system]
    - role: nginx
      tags: [system]
    - role: sshd
      tags: [system]
    - role: certbot
      when: configure_tls
      tags: [system]
    - role: interactive_tools
      tags: [system]
    - role: podman
      tags: [system]
    - role: jenkins
      tags: [user, jenkins]
    - role: grafana
      tags: [user, grafana]
