- name: Service deployment
  hosts: all
  roles:
    - role: dnf
      when: '"fedora" in group_names'
      tags: [system]
    - role: firewalld
      tags: [system]
    - role: unprivileged_user
      tags: [system]
    - role: nginx
      tags: [system]
    - role: sshd
      tags: [system]
    - role: certbot
      when: configure_tls
      tags: [system]
    - role: interactive_tools
      tags: [system]
    - role: podman
      tags: [system]
    - role: jenkins
      tags: [user]
    - role: grafana
      tags: [user]
